on:
  push:
    branches:
      - master
  pull_request:

name: CI

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  checks:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      #- run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy

  # TODO: might not build on Linux
  #build:
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: dtolnay/rust-toolchain@stable
  #    - uses: Swatinem/rust-cache@v2
  #    - run: cargo build

  spell-check:
    name: Spell Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.4